/* eslint-disable @next/next/no-img-element */
import Footer from '@/components/navigation/Footer';
import Header from '@/components/navigation/Header';
import Head from 'next/head';

function Home() {
  return (
    <>
      <Head>
        <title>Contact - Realverse Associate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <section>
        <div className="max-w-4xl px-5  md:px-10 mx-auto pt-6 md:pt-10 pb-20">
          <h1 className="text-2xl md:text-4xl text-center font-extrabold text-amber-500">
            About Us
          </h1>
          <hr className="my-2 border-temp-violet border-2 sm:mx-auto" />

          <div className="mt-6 grid gap-y-4">
            <p>
              Welcome to Realverse Associate, your one-stop solution for legal
              documentation and paperwork needs. We are a team of experienced
              professionals committed to providing reliable, efficient, and
              affordable services to help businesses and individuals thrive.
            </p>
            <p>
              Our company was founded in 2022 by Akshay Mishra, a seasoned
              entrepreneur with a passion for simplifying complex legal
              processes. Since then, we have helped hundreds of clients across
              various industries to streamline their paperwork and focus on what
              matters most - growing their business.
            </p>
            <p>
              At Realverse Associate, we believe that every client deserves
              personalized attention and tailored solutions. We take the time to
              understand your unique needs and goals, and we work closely with
              you to ensure that our services meet or exceed your expectations.
            </p>
            <p>
              We pride ourselves on our customer-centric approach and our
              commitment to delivering high-quality services at competitive
              prices. But don&apos;t just take our word for it - check out our
              testimonials page to see what our clients have to say about us.
            </p>
            <p>
              Whether you are a startup entrepreneur, a small business owner, or
              an individual seeking legal documentation services, we are here to
              help. Contact us today to learn more about how we can support your
              success.
            </p>
          </div>
        </div>
      </section>
      <section>
        <div className="max-w-4xl px-5  md:px-10 mx-auto pt-6 md:pt-10 pb-28">
          <h1 className="text-2xl md:text-4xl text-center font-extrabold text-amber-500">
            Meet Our Team
          </h1>
          <hr className="my-2 border-temp-violet border-2 sm:mx-auto" />
          <div className="mt-6 flex justify-around">
            <div>
              <h1>Akshay Mishra</h1>
            </div>
            <div>
              <h1>Kadum Komut</h1>
            </div>
          </div>
        </div>
      </section>

      {/* footer */}
      <Footer />
    </>
  );
}

export default Home;
