import CategoryLayout from '@/components/layout/CategoryLayout';
import {
  CategoryPageCTA,
  CategoryPageWhatsIncluded,
} from '@/components/utility/CategoryPageUtility';
import WhyChoose from '@/components/utility/WhyChoose';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <CategoryLayout>
        <Head>
          <title>
            Accounting and Book Keeping Services - Realverse Associate
          </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <CategoryPageCTA title="Accounting & MIS" price="4,999">
          <li>Mandatory for Specified Businesses and Services</li>
          <li>Ensures timely and accurate compliance</li>
          <li>Get real-time financial health</li>
          <li>Helps track business performance</li>
        </CategoryPageCTA>
        <CategoryPageWhatsIncluded title="What's Included?">
          <ul className="list-image-[url(/icons/caret.png)]">
            <li className="mb-2">Accounting in Tally / Quick Books</li>
            <li className="mb-2">Customised MIS on Monthly basis</li>
            <li className="mb-2">Monthly Cash Flows</li>
            <li>Flagging of Debtor and Creditor Issues</li>
          </ul>
          <ul className="list-image-[url(/icons/caret.png)]">
            <li className="mb-2">Free GST Registration</li>
            <li className="mb-2">Free Import Export Code (IEC)</li>
            <li className="mb-2">Free Udyog Aadhar Certificate</li>
            <li>Free PT Registration</li>
          </ul>
          <ul className="list-image-[url(/icons/caret.png)]">
            <li className="mb-2 list-image-none font-bold">
              20% Discount on:{' '}
            </li>
            <li className="mb-2">Private Limited Incorporation</li>
            <li className="mb-2">Annual Compliances</li>
            <li>Business Plan & DPIIT Registration</li>
          </ul>
        </CategoryPageWhatsIncluded>
        <WhyChoose className="bg-primary-light" />
        <CategoryPageWhatsIncluded title="Documents Required">
          <ul className="list-image-[url(/icons/caret.png)]">
            <li className="mb-2">Cash Books</li>
            <li className="mb-2">Bank Statements</li>
            <li className="mb-2">All Invoice Copies</li>
            <li>Loan Statements</li>
          </ul>

          <ul className="list-image-[url(/icons/caret.png)]">
            <li className="mb-2">Deposit Slips</li>
            <li className="mb-2">Purchase Orders</li>
            <li>Credit Memos</li>
          </ul>

          <ul className="list-image-[url(/icons/caret.png)]">
            <li className="mb-2">Receipts Details</li>
            <li className="mb-2">Investment Details</li>
            <li>Fixed Asset Register</li>
          </ul>
        </CategoryPageWhatsIncluded>
      </CategoryLayout>
    </>
  );
}
