/* eslint-disable @next/next/no-img-element */
import Footer from '@/components/navigation/Footer';
import Header from '@/components/navigation/Header';
import Head from 'next/head';

function Home() {
  return (
    <>
      <Head>
        <title>Contact - Realverse Associate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <section>
        <div className="max-w-6xl px-5  md:px-10 mx-auto pt-6 md:pt-10 pb-28">
          <h1 className="text-2xl md:text-4xl text-center font-extrabold text-amber-500">
            Contact Us
          </h1>
          <div className="grid md:flex md:justify-between mt-6 gap-x-4 gap-y-6 ">
            <form className="text-sm grid gap-y-4 flex-1">
              <div className="grid gap-y-2">
                <label className="font-medium">Name</label>
                <input type="text" placeholder="john doe" className="" />
              </div>
              <div className="grid gap-y-2">
                <label className="font-medium">Email</label>
                <input
                  type="text"
                  placeholder="johndoe@gmail.com"
                  className=""
                />
              </div>
              <div className="grid gap-y-2">
                <label className="font-medium">Phone</label>
                <input type="number" placeholder="88333....." className="" />
              </div>
              <div className="grid gap-y-2">
                <label className="font-medium">Message</label>
                <textarea
                  type="number"
                  placeholder="Enter your message"
                  className=""
                  rows={3}
                />
              </div>
              <div>
                <button className="bg-blue-600 hover:bg-blue-700 py-2 px-14 text-lg text-white">
                  Submit
                </button>
              </div>
            </form>
            <div className="flex justify-center">
              <img
                src="/images/Getintouch.gif"
                alt="contact us"
                className="w-10/12"
              />
            </div>
          </div>
        </div>
      </section>

      <section className="bg-temp-violet/5">
        <div className="max-w-7xl px-2 service-category-lg:px-4 mx-auto pt-28 pb-28">
          <h1 className="text-2xl md:text-4xl text-center font-extrabold text-amber-500">
            Our Office
          </h1>
          <div className="grid service-category-lg:grid-cols-contactTemplate mt-6  gap-x-3">
            <div className="border px-4 py-5 flex flex-col gap-y-2 bg-white text-temp-violet-dark">
              <h1 className="text-2xl text-center font-medium">Address</h1>
              <p>
                A-201, 2nd Floor, Galore Tech Lohia-Jain Bldg., Chandni Chowk,
                Bavdhan (Khurd), Pune-411021, Maharashtra, India.
              </p>
              <p>080-69428002</p>
              <p>enquiry@realverseassociate.com</p>
            </div>
            <div className="border bg-white h-60">
              <img
                src="/images/fake-google-map.png"
                alt="fake google map"
                className="w-full h-full object-center object-cover"
              />
            </div>
          </div>
        </div>
      </section>

      {/* footer */}
      <Footer />
    </>
  );
}

export default Home;
